on: [push]
name: "VarDump Checker"

jobs:
  var_dump_checker:
    runs-on: ubuntu-latest
    name: Check
    steps:
    - name: Check 1
      id: check1
      uses: umutphp/php-var-dump-check-action@master
      with:
        checktype: 'none'
        exclude: '.github'
        extensions: 'md,yml,sh'